name: gamegoapp
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.0-257.0.dev <4.0.0'
  
dependencies:
  chat_bubbles:
  badges: ^3.0.2
  cloud_firestore: ^4.4.2
  firebase_core: ^2.6.1
  firebase_storage: ^11.0.13
  path: ^1.8.2
  jiffy: ^5.0.0
  firebase_messaging: ^14.2.4
  flutter_local_notifications: ^13.0.0
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.17
  google_sign_in: ^6.0.1
  flutter_launcher_icons: ^0.11.0
  webview_flutter: ^4.0.2
  cupertino_icons:
  dropdown_button2:
  flutter:
    sdk: flutter
  flutter_multi_select_items:
  flutter_slidable:
  font_awesome_flutter:
  get:
  mask_text_input_formatter:
  multi_select_flutter:
  settings_ui:
  syncfusion_flutter_gauges:
  firebase_analytics: ^10.1.3
  firebase_auth: ^4.2.0
  firebase_app_installations: ^0.2.1+11
  image_picker: ^0.8.5+3
  grouped_list: ^5.1.2
  table_calendar: ^3.0.8
  flutter_time_picker_spinner: ^2.0.0
  change_app_package_name: ^1.1.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    # λ…Έν†  μ‚°μ¦ kr
    - family: NotoSansCJKkr
      fonts:
        - asset: assets/fonts/NotoSansCJKkr-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansCJKkr-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansCJKkr-Bold.otf
          weight: 600
        # - asset: assets/fonts/NotoSansCJKkr-Thin.otf
        #   weight: 100
        # - asset: assets/fonts/NotoSansCJKkr-Light.otf
        #   weight: 200
        # - asset: assets/fonts/NotoSansCJKkr-DemiLight.otf
        #   weight: 300
        # - asset: assets/fonts/NotoSansCJKkr-Black.otf
        #   weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path_android: "assets/app_icon/app_icon.png"
  adaptive_icon_background: "assets/app_icon/icon_background.png"
  adaptive_icon_foreground: "assets/app_icon/icon_foreground.png"
